destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex
topicTitlePre:  '<h3>/* '
topicTitlePost: '<br />&nbsp;* ------------------------------------------ */</h3>'
rightTopicTitlePre:  '<h3>/* '
rightTopicTitlePost: '<br />&nbsp;* ------------- */</h3>'
topicSubtitlePre: '<h4>'
topicSubtitlePost: '</h4>'
url: 'http://dev.tritarget.org'
postImagesPath: '/images/post_images'
screenSaver: true
disqusComments: true
debug: false
