destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex
postImagesPath: '/images/post_images'
url: 'http://dev.tritarget.org'
title: TriTarget Development
author:
  name: Devin Weaver (Sukima)
  email: suki@tritarget.org
debug: false
theme: redmond

# features:
google:
  analytics:
    enabled: true
    id: "UA-25176709-2"
  search:
    enabled: true
    domain: "dev.tritarget.org"

screenasver:
  enabled: true

disqus:
  enabled: true

ski:
  enabled: true

twitter:
  enabled: true
