destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex
googleSiteSearch: 'dev.tritarget.org'
url: 'http://dev.tritarget.org'
title: TriTarget Development
author:
  name: Devin Weaver (Sukima)
  email: suki@tritarget.org
postImagesPath: '/images/post_images'
enableScreenSaver: false
enableDisqusComments: true
enableGoogleSearch: true
enableTwitter: true
enableSki: true
debug: false
theme: redmond
