# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tritarget.org
title: TriTarget
subtitle: A blog of personal quality
author: Devin Weaver
simple_search: http://google.com/search
description: "My personal blog of random musings. From software development to creative writing to just what's on my mind."

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
category_feeds: false
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown
pygments: false # Jekyll's default Python Pygments have been replaced by pygments.rb. Set to true to use Albino + Pythong Pygments

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: blog_index_default.html
page_sidebar: page_default.html
post_sidebar: post_default.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Javascript social buttons often generate lots of http requests and may track your viewer's browsing history
# Show respect for privacy and bandwidth with simple links for Twitter, Facebook and Google Plus.
respectfully_social: true

# Jquery Theme
jqueryui_theme: base

# Github repositories
github_user: sukima
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true

# Twitter
# twitter_user: sukima
# twitter_tweet_count: 4
# twitter_show_replies: false
# twitter_follow_button: true
# twitter_show_follower_count: false
# twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
google_plus_user: 104981501099138892251
google_plus_image_size: 32

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: devtritargetorg
disqus_show_comment_count: true
disqus_developer: 0

# Google Analytics
google_analytics_tracking_id: UA-30456823-1

# Gaug.es Analytics
gauges_analytics_tracking_id:

# Facebook Like
facebook_like: true

# Flickr Photos
flickr_userid: 55325630@N02
flickr_nickname: SirSuki
flickr_apikey: 631ea8b903507b0dedec09169d5774e5
flickr_count: 3

# Gravatar plugin
gravatar_hash: a33233f156a5531707f130c28565de69

# Photos CDN
photos_prefix: "http://photos.tritarget.org/photos/"
salado_player: "http://photos.tritarget.org/salado/SaladoPlayer-1.3.swf"
panos_prefix: "http://photos.tritarget.org/panoramas/"

# PGP
pgp_key_id: "DE767C8A"
pgp_fingerprint1: "FA9F 1400 8BA5 A847 B097"
pgp_fingerprint2: "7C06 EBD9 9C92 DE76 7C8A"
